#!/usr/bin/env sh
elinks --dump $1 |sed '/Visible links/,$ {
s|https://urldefense.*url?u=||
s|-3A.*3A|:|
s|_|/|g
s|&d=.*||g
s|-23|#|g
s|-24|$|g
s|-26|\&|g
s|-2A|\*|g
s|-2B|\+|g
s|-2C|,|g
s|-2F|/|g
s|-3B|;|g
s|-3D|=|g
s|-3F|?|g
s|-40|@|g
s|-5B|[|g
s|-5D|]|g
s|-2D|-|g
s|-20| |g
s|-22|"|g
s|-25|%|g
s|-2E|\.|g
s|-5F|_|g
s|-3A|:|g
s|-7E|~|g}'
