sudo pip install -U numpy
sudo pip install -U matplotlib
sudo pip install -U nltk
sudo pip install -U twitter
sudo pip install -U scipy
sudo pip install -U pandas
sudo pip install -U beautifulsoup4
sudo pip install -U lxml
sudo pip install -U scikit-learn
sudo pip install -U django
sudo pip install -U djangorestframework
